### PR TITLE
Split mouse_diff api into cursor_diff and mouse_diff

### PR DESCRIPTION
**Pull request by agorgl**
Implements suggestion described in #12

### CODE REVIEW

**Comment by rukai** [comment]
Thanks for the PR!

If the only difference between `WindowEvent::CursorMoved` and `DeviceEvent::MouseMotion` is that `MouseMotion` reports changes even when the cursor is locked then lets just replace `CursorMoved` with `MouseMotion`.
I cant think of a use case for ignoring motion only when the cursor is locked.

It seems you have your IDE set to auto run `cargo fmt` which is making it hard to find the real changes in your PR.
I will solve this by just getting with the times and `cargo fmt`ifying the whole codebase.
Hope the merge conflicts arent too much trouble...

**Comment by ElArtista** [comment]
You can always check the second commit, thats why I did them separately

**Comment by rukai** [comment]
Oh I didnt notice there was two commits, sorry :(

**Comment by rukai** [comment]
Closing as abandoned.

**Pull request closed without merging**
